title: MondoKit
description: Simplify building NodeJS applications on cloud platforms
theme: just-the-docs

logo: "/assets/images/mondokit-with-name.png"
favicon_ico: "/assets/images/mondokit-logo.ico"
aux_links:
  "MondoKit on GitHub":
    - "//github.com/mondo-mob/mondokit"

aux_links_new_tab: true
color_scheme: dark
